config/routes.rb
Rails.application.routes.draw do

  resources :inquiries

  root "pages#home"

  get "squad" => "pages#squad"
  get "space" => "pages#space"

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def index
  end

  def new
  end

  def create
     @inquiry = Inquiry.create(inquiry_params)

     @inquiry.save
     redirect_to @inquiry
  end

  def show
  end

  def edit
  end

  def destory
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:first_name, :last_name, :message)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @inquiry = Inquiry.new
  end

  def squad
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/inquiries/show.html.erb
<iframe src="//giphy.com/embed/VFnPXXSrtALNm" width="480" height="501" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
<br><br>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    supplying love and <span class="service"></span> from houston.
  </div>
</div>

<script>
$(function(){
      $(".service").typed({
          strings: ["branding", "strategy", "marketing", "growth"],
          typeSpeed: -2,
          loop: true,
          cursorChar: " ❤"
      });
  });
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= link_to image_tag("straight_up_v1.png", height: "60", id: "logo"), root_path, class: "image-responsive" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "home", root_path %></li>
        <li><%= link_to "squad", squad_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>straightUp growth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'typed' %>
  <link href="https://fonts.googleapis.com/css?family=Oswald|Satisfy" rel="stylesheet">
  <%= csrf_meta_tags %>
  <script src="https://aframe.io/releases/latest/aframe.min.js"></script>
  <script src="https://raw.githubusercontent.com/subsumo/aframe-orbit-controls/master/dist/aframe-orbit-controls-component.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>



  <%= render 'layouts/header' %>


  <div class="container">
    <h1 class="main-header">we're all about the <span style="background-color:black;color:white;">growth.</span></h1>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/home.html.erb
  <br><br>
  <!-- <div class="row">
    <div id="#left"class="one-half column">
      <p class="process">listen to your story</p>
      <p class="process">assess your needs</p>
      <p class="process">chart a map for your growth</p>
      <p class="process">straight up execute</p>
      <p class="process">measure your growth</p>
    </div>
    <div id="#right"class="one-half column">
      <p class="statement">there comes a time when it's incumbent to start something fresh,</p>
      <p class="statement">an idea that sat there ... gathering dust.</p>
      <p class="statement">we will never change the world if we sleep on our dreams.</p>
      <p class="final-statement">allow us to manifest your vision.</p>
    </div> -->
    <%= form_for :inquiry, url: inquiries_path do |f| %>
    <div class="row">
      <div class="one-half column">
        <p><%= f.label :first_name, "First Name" %>
           <%= f.text_field :first_name %>
        </p>
        <p><%= f.label :last_name, "Last Name" %>
           <%= f.text_field :last_name %>
        </p>
        <p><%= f.label :message, "What does growth mean to you?" %>
           <%= f.text_area :message %>
        </p>
      </div>
      <div class="one-half column">
        <%= f.submit "😵", class: "submit-button" %>
      </div>
    </div>
    <% end %>

app/views/pages/space.html.erb
<h1 style="color:black">our process</h1>

<a-scene vr-mode-ui="enabled: false">
  <a-sky src=<%= image_path "skyscraper.jpg" %> rotation="0 -130 0"></a-sky>
</a-scene>

<br><br>

app/views/pages/squad.html.erb
<div class="container">

  <div class="row who-we-are">
      <p class="blurb">Born out of Houston, StraightUp Growth was founded by a group of four friends who realized that businesses who seek to thrive in this competitive economy, need a certain set of basic elements that will set them apart from old and fading companies ... <span class="straight-up">straight up</span>. It's almost as if you're doomed to fail unless you adopt those elements. We've curated strategies, analyzed several companies, and are here to help you grow ... <span class="straight-up">straight up</span> to the top. Its the only direction on our GPS. Let's go north and leave the competitors at the bottom.</p>
  </div>

  <div class="row bio-pics">
    <div class="one-half column"><%= image_tag "bios/allen.jpg", :class => "bio-pic" %></div>
    <div class="one-half column"><%= image_tag "bios/zubair.jpg", :class => "bio-pic" %></div>
  </div>

  <div class="row bio-descs">
    <div class="one-half column bio-desc">Allen's Desc</div>
    <div class="one-half column bio-desc">Zubair's Desc</div>      
  </div>

  <div class="row bio-pics">
    <div class="one-half column"><%= image_tag "bios/ar.jpg", :class => "bio-pic" %></div>
    <div class="one-half column"><%= image_tag "bios/kazee.jpg", :class => "bio-pic" %></div>
  </div>

  <div class="row bio-descs">
    <div class="one-half column bio-desc">AR's Desc</div>
  </div>
  
</div>